[theme]
base = "light"  # Define o tema claro como padrão
backgroundColor = "#FFFFFF"  # Fundo branco
secondaryBackgroundColor = "#F0F0F0"  # Fundo secundário (ex.: barra lateral)
textColor = "#000000"  # Texto preto
font = "sans serif"  # Fonte padrão
